#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    exit 1;
fi;

# rodar os testes
./vendor/bin/pest --parallel
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
    exit 1;
fi;

exit 0;
